[package]
name = "hotcorn"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
confy = "1.0.0"
hyprland = "0.4.0-beta.3"
